title: John Ndung'u Kiarie
description: "TryHackMe & HTB writeups"
baseurl: ""        # keep empty for user site
url: "https://john4kiarie.github.io"

# simple navigation (used in layout)
menu:
  - title: "Home"
    url: "/"
  - title: "Writeups"
    url: "/writeups/"

plugins:
  - jekyll-feed
